### ISSUE TITLE
某些division不存在

### ISSUE THREAD

**Issue by wisetwo** [cn/GB2260.js#1]
某些division在所有json中都查不到数据，如1986年登记的412828就没有数据，是否缺失某些历史版本的数据？

**Comment by tonyseek** [comment]
是的，已经废弃的行政编号没有可以公开查询的地方了。我们从互联网档案馆里找到了一些，正在手动整理，完成后会提交进来。

**Comment by wisetwo** [comment]
这个不错，包含历史的，比较全：http://www.zxinc.org/gb2260.htm
我试用了下，都可以查，历史的revision对应的地址带[]符号，可以考虑把这个加入为一个特殊版：）

**Comment by tonyseek** [comment]
[gitter](https://gitter.im/cn/GB2260) 中讨论过这个问题，来自互联网档案馆的数据（GB/T 2260-1999）是国家统计局公布过的，会更加权威准确。

数据整理和实现规范相关的问题请在 https://github.com/cn/GB2260 反馈，也欢迎参与相关工作。

**Comment by wisetwo** [comment]
好的：）
