### ISSUE TITLE
切换 revision 的问题

### ISSUE THREAD

**Issue by uwang** [cn/GB2260.js#6]
实际使用如下

```js
var gb2260 = require('gb2260');

// register revision data
gb2260.register('201410', require('gb2260/lib/201410'));

var gb = new gb2260.GB2260();//文档里的 revision 不知道是什么东东，不传都可以啊
gb.get('430421');
```

难道不能只传入一个参数来切换 revision 么？实际使用中可能需要在多个 年份的 数据中切换，类似于下面这种使用方法。

```js
var gb2260 = require('gb2260');
var revisions = gb2260.revisions();
var gb = new gb2260.GB2260(revisions[0]);
gb.get('430421');
// 如果查不到数据可以依次从 revisions[0] 切换到 revisions[revisions.length-1] 查询
```

还有就是，README 文档中写得不是很清楚

## Usage

```js
var gb2260 = require('gb2260');
// register revision data
gb2260.register('201410', require('gb2260/lib/201410'))
```

## GB2260

```js
var gb = new gb2260.GB2260(revision);
```

Usage 和 GB2260 中间明显是中断的感觉啊

- gb2260.register 必须传入两个参数么？
- gb2260.GB2260(revision) 中的 revision 传入数据是什么？是可选的么？

如果能得到回答，不尽感激，谢谢

**Comment by lepture** [comment]
因爲 JS 在 browser 裏也會被用到，所以把數據與邏輯分開來了，當你調用

```
gb2260.register('201410', require('gb2260/lib/201410'))
```

即是注冊了 201410 的數據，這個時候 `var gb = new gb2260.GB2260('201410')` 才能正常獲取數據。

----

> 文档里的 revision 不知道是什么东东，不传都可以啊

這是因爲 revision 的默認值是 201410，revision 的概念會在下一版本調整。目前的定義見 spec: https://github.com/cn/GB2260/blob/v0.2/spec.md


> 如果查不到数据可以依次从 revisions[0] 切换到 revisions[revisions.length-1] 查询

revision 是必須一定的，不能依次查詢。每一版的數據都是一個完整的固定值，不能混合使用。

**Comment by uwang** [comment]
了解了，感谢。
